/**
 * Finding DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: findings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Finding DTOs
 *
 * DDD: Application DTOs for Finding use cases.
 */

import type { FindingCreateRequest, GetFindingParams, ListFindingsParams } from "@vericlause/core/findings/types";

export type ListFindingsInput = ListFindingsParams;

export type CreateFindingInput = FindingCreateRequest;

export type GetFindingInput = GetFindingParams;

export type ListFindingsOutput = {};

export type CreateFindingOutput = {};

export type GetFindingOutput = {};
