/**
 * GetAssuranceArtefact handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getAssuranceArtefact } from "@vericlause/api-server/domains/assurance-artefacts/handlers";
import type { AssuranceArtefactsDDDDependencies } from "@vericlause/api-server/domains/assurance-artefacts";
import { createAssuranceArtefact as createAssuranceArtefactEntity } from "@vericlause/factories/assurance-artefacts";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@vericlause/tests/shared";
import { ASSURANCEARTEFACTS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetAssuranceArtefact", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AssuranceArtefactsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AssuranceArtefactsDDDDependencies>(
      ASSURANCEARTEFACTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createAssuranceArtefactEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetAssuranceArtefact, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { artefactId: entity.id };

    await getAssuranceArtefact(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetAssuranceArtefact.execute).toHaveBeenCalledWith(expect.objectContaining({ artefactId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { artefactId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetAssuranceArtefact, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getAssuranceArtefact(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
