/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./create-assurance-artefact.handler.test.js";
export * from "./get-assurance-artefact.handler.test.js";
export * from "./list-assurance-artefacts.handler.test.js";
