/**
 * Dependency Container
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Manages dependency creation and caching per domain.
 */

import type { AdapterDynamoDBClient } from "@vericlause/adapters";
import { getDynamoClientInstance } from "../lib/dependencies/domain-dependencies.js";
import { executionContextService } from "../lib/context/execution-context.service.js";
import {
  buildAnalysisJobsDomainModule,
  buildAssuranceArtefactsDomainModule,
  buildContractProjectsDomainModule,
  buildFindingsDomainModule,
  buildIdentityDomainModule,
  buildReleaseGatesDomainModule,
  buildSpecificationsDomainModule,
  buildWaiversDomainModule,
} from "../domains/index.js";
import type {
  AnalysisJobsDomainModule,
  AssuranceArtefactsDomainModule,
  ContractProjectsDomainModule,
  FindingsDomainModule,
  IdentityDomainModule,
  ReleaseGatesDomainModule,
  SpecificationsDomainModule,
  WaiversDomainModule,
} from "../domains/index.js";

class DependencyContainer {
  private readonly dynamoClient: AdapterDynamoDBClient;

  private analysisJobsModule: AnalysisJobsDomainModule | null = null;
  private assuranceArtefactsModule: AssuranceArtefactsDomainModule | null = null;
  private contractProjectsModule: ContractProjectsDomainModule | null = null;
  private findingsModule: FindingsDomainModule | null = null;
  private identityModule: IdentityDomainModule | null = null;
  private releaseGatesModule: ReleaseGatesDomainModule | null = null;
  private specificationsModule: SpecificationsDomainModule | null = null;
  private waiversModule: WaiversDomainModule | null = null;

  constructor(dynamoClient: AdapterDynamoDBClient) {
    this.dynamoClient = dynamoClient;
  }

  /**
   * Get analysis-jobs domain module
   */
  getAnalysisJobsDependencies(): AnalysisJobsDomainModule {
    if (!this.analysisJobsModule) {
      this.analysisJobsModule = buildAnalysisJobsDomainModule(this.dynamoClient);
    }
    return this.analysisJobsModule;
  }

  /**
   * Get assurance-artefacts domain module
   */
  getAssuranceArtefactsDependencies(): AssuranceArtefactsDomainModule {
    if (!this.assuranceArtefactsModule) {
      this.assuranceArtefactsModule = buildAssuranceArtefactsDomainModule(this.dynamoClient);
    }
    return this.assuranceArtefactsModule;
  }

  /**
   * Get contract-projects domain module
   */
  getContractProjectsDependencies(): ContractProjectsDomainModule {
    if (!this.contractProjectsModule) {
      this.contractProjectsModule = buildContractProjectsDomainModule(this.dynamoClient);
    }
    return this.contractProjectsModule;
  }

  /**
   * Get findings domain module
   */
  getFindingsDependencies(): FindingsDomainModule {
    if (!this.findingsModule) {
      this.findingsModule = buildFindingsDomainModule(this.dynamoClient);
    }
    return this.findingsModule;
  }

  /**
   * Get identity domain module
   */
  getIdentityDependencies(): IdentityDomainModule {
    if (!this.identityModule) {
      this.identityModule = buildIdentityDomainModule(this.dynamoClient);
    }
    return this.identityModule;
  }

  /**
   * Get release-gates domain module
   */
  getReleaseGatesDependencies(): ReleaseGatesDomainModule {
    if (!this.releaseGatesModule) {
      this.releaseGatesModule = buildReleaseGatesDomainModule(this.dynamoClient);
    }
    return this.releaseGatesModule;
  }

  /**
   * Get specifications domain module
   */
  getSpecificationsDependencies(): SpecificationsDomainModule {
    if (!this.specificationsModule) {
      this.specificationsModule = buildSpecificationsDomainModule(this.dynamoClient);
    }
    return this.specificationsModule;
  }

  /**
   * Get waivers domain module
   */
  getWaiversDependencies(): WaiversDomainModule {
    if (!this.waiversModule) {
      this.waiversModule = buildWaiversDomainModule(this.dynamoClient);
    }
    return this.waiversModule;
  }

  clearAnalysisJobsDependencies(): void { this.analysisJobsModule = null; }
  clearAssuranceArtefactsDependencies(): void { this.assuranceArtefactsModule = null; }
  clearContractProjectsDependencies(): void { this.contractProjectsModule = null; }
  clearFindingsDependencies(): void { this.findingsModule = null; }
  clearIdentityDependencies(): void { this.identityModule = null; }
  clearReleaseGatesDependencies(): void { this.releaseGatesModule = null; }
  clearSpecificationsDependencies(): void { this.specificationsModule = null; }
  clearWaiversDependencies(): void { this.waiversModule = null; }

  getAnalysisJobsDependenciesForRequest(): AnalysisJobsDomainModule {
    return this.getAnalysisJobsDependencies();
  }

  getAssuranceArtefactsDependenciesForRequest(): AssuranceArtefactsDomainModule {
    return this.getAssuranceArtefactsDependencies();
  }

  getContractProjectsDependenciesForRequest(): ContractProjectsDomainModule {
    return this.getContractProjectsDependencies();
  }

  getFindingsDependenciesForRequest(): FindingsDomainModule {
    return this.getFindingsDependencies();
  }

  getIdentityDependenciesForRequest(): IdentityDomainModule {
    return this.getIdentityDependencies();
  }

  getReleaseGatesDependenciesForRequest(): ReleaseGatesDomainModule {
    return this.getReleaseGatesDependencies();
  }

  getSpecificationsDependenciesForRequest(): SpecificationsDomainModule {
    return this.getSpecificationsDependencies();
  }

  getWaiversDependenciesForRequest(): WaiversDomainModule {
    return this.getWaiversDependencies();
  }

  /**
   * Clear all caches
   */
  clearAllCaches(): void {
    this.analysisJobsModule = null;
    this.assuranceArtefactsModule = null;
    this.contractProjectsModule = null;
    this.findingsModule = null;
    this.identityModule = null;
    this.releaseGatesModule = null;
    this.specificationsModule = null;
    this.waiversModule = null;
  }
}

let dependencyContainerInstance: DependencyContainer | null = null;

export function getDependencyContainer(): DependencyContainer {
  if (!dependencyContainerInstance) {
    const dynamoClient = getDynamoClientInstance();
    dependencyContainerInstance = new DependencyContainer(dynamoClient);
  }
  return dependencyContainerInstance;
}
