/**
 * Routes for Accept
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: specifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { acceptInferredSpecification } from "../handlers/accept.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function acceptRoutes(fastify: FastifyInstance) {
  // POST /v1/specifications/{specId}/accept (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/specifications/:specId/accept",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { specId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getSpecificationsDependenciesForRequest();
        await acceptInferredSpecification(request, reply, deps);
      });
    }
  );


}
