/**
 * ReleaseGate Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: release-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/release-gates.openapi.types.js";
import { schemas } from "../schemas/release-gates.schemas.js";

/**
 * Entity: ReleaseGateEntity
 * Description: Represents the ReleaseGate domain model.
 * Source: schemas.ReleaseGate
 * Type: Domain Entity (API)
 */
export const ReleaseGateEntitySchema = schemas.ReleaseGate;
export type ReleaseGateEntity = components["schemas"]["ReleaseGate"];
