/**
 * Specifications DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: specifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Specifications Domain Module - Composition root
 *
 * DDD: Composition root for specifications domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AcceptRepositoryAdapter,
  SpecificationRepositoryAdapter,
} from "@vericlause/adapters/specifications";
import { getIdGeneratorService } from "@vericlause/adapters";
import type { AdapterDynamoDBClient } from "@vericlause/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteAcceptInferredSpecification,
  ExecuteCreateSpecification,
  ExecuteGetSpecification,
  ExecuteListSpecifications,
  ExecuteUpdateSpecification,
} from "@vericlause/services/specifications/usecases";
// Ports (interfaces)
import type {
  AcceptRepository,
  SpecificationRepository,
} from "@vericlause/services/specifications/ports";

export interface SpecificationsDomainModule {
  repos: {
    accepts: AcceptRepository;
    specifications: SpecificationRepository;
  };
  useCases: {
    accepts: {
      get: ExecuteAcceptInferredSpecification;
    };
    specifications: {
      create: ExecuteCreateSpecification;
      get: ExecuteGetSpecification;
      list: ExecuteListSpecifications;
      update: ExecuteUpdateSpecification;
    };
  };
}

export function buildSpecificationsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): SpecificationsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      accepts?: AcceptRepository;
      specifications?: SpecificationRepository;
    } = {};

    obj.accepts = new AcceptRepositoryAdapter(dynamoClient);
    obj.specifications = new SpecificationRepositoryAdapter(dynamoClient);
    return {
      accepts: obj.accepts!,
      specifications: obj.specifications!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    accepts: {
      get: new ExecuteAcceptInferredSpecification(executionContext, idGenerator, repos.accepts),
    },
    specifications: {
      create: new ExecuteCreateSpecification(executionContext, idGenerator, repos.specifications),
      get: new ExecuteGetSpecification(executionContext, idGenerator, repos.specifications),
      list: new ExecuteListSpecifications(executionContext, idGenerator, repos.specifications),
      update: new ExecuteUpdateSpecification(executionContext, idGenerator, repos.specifications),
    },
  };
  return { repos, useCases: useCases as SpecificationsDomainModule["useCases"] };
}
