/**
 * UpdateContractProject handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contract-projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { updateContractProject } from "@vericlause/api-server/domains/contract-projects/handlers";
import type { ContractProjectsDDDDependencies } from "@vericlause/api-server/domains/contract-projects";
import { createContractProject as createContractProjectEntity } from "@vericlause/factories/contract-projects";
import { createUpdateContractProjectRequest } from "@vericlause/factories/contract-projects";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@vericlause/tests/shared";
import { CONTRACTPROJECTS_USE_CASES } from "../__factories__/use-cases.js";

describe("UpdateContractProject", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ContractProjectsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ContractProjectsDDDDependencies>(
      CONTRACTPROJECTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with updated entity", async () => {
    const entity = createContractProjectEntity({ orgId });
    const input = createUpdateContractProjectRequest();
    const updatedEntity = { ...entity, ...input };
    const useCaseResult = { data: updatedEntity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.params = { projectId: entity.id };
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeUpdateContractProject, "execute").mockResolvedValue(useCaseResult);

    await updateContractProject(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeUpdateContractProject.execute).toHaveBeenCalledWith(expect.objectContaining({ projectId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
