/**
 * SpecificationRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: specifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SpecificationRepository Port
 *
 * DDD: Application port for specificationrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateSpecificationInput, CreateSpecificationOutput, GetSpecificationInput, GetSpecificationOutput, ListSpecificationsInput, ListSpecificationsOutput, UpdateSpecificationInput, UpdateSpecificationOutput } from "../dto/specification.dto";
export interface SpecificationRepository {
  listSpecifications(input: ListSpecificationsInput): Promise<ListSpecificationsOutput>;
  createSpecification(input: CreateSpecificationInput): Promise<CreateSpecificationOutput>;
  getSpecification(input: GetSpecificationInput): Promise<GetSpecificationOutput>;
  updateSpecification(input: UpdateSpecificationInput): Promise<UpdateSpecificationOutput>;
}

export type { CreateSpecificationInput, CreateSpecificationOutput, GetSpecificationInput, GetSpecificationOutput, ListSpecificationsInput, ListSpecificationsOutput, UpdateSpecificationInput, UpdateSpecificationOutput } from "../dto/specification.dto";
