/**
 * ExecuteCreateAuditorExportPack - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateAuditorExportPack Use Case
 *
 * DDD: Application use case for create AuditorExport.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateAuditorExportPackInput, CreateAuditorExportPackOutput } from "../dto/auditor-export.dto";
import type { ExecutionContextService, IdGeneratorService } from "@vericlause/services/_shared/index.js";
import type { AuditorExportRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateAuditorExportPack {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly auditorExport: AuditorExportRepository
  ) {}

  async execute(input: CreateAuditorExportPackInput): Promise<CreateAuditorExportPackOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.artId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    // No required field validations    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (assurance-artefacts domain)
    const entityId = this.idGenerator.artId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.auditorExport.createAuditorExportPack({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateAuditorExportPackOutput;
  }
}
