/**
 * ExecuteSignAssuranceArtefact - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteSignAssuranceArtefact Use Case
 *
 * DDD: Application use case for get Sign.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { SignAssuranceArtefactInput, SignAssuranceArtefactOutput } from "../dto/sign.dto";
import type { ExecutionContextService, IdGeneratorService } from "@vericlause/services/_shared/index.js";
import type { SignRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteSignAssuranceArtefact {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly sign: SignRepository
  ) {}

  async execute(input: SignAssuranceArtefactInput): Promise<SignAssuranceArtefactOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.artId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).artefactId) {
      throw new ValidationError("artefactId is required");
    }
    const artefactId = (input as any).artefactId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.sign.signAssuranceArtefact({ artefactId: artefactId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${artefactId}`);
    }

    return entity as SignAssuranceArtefactOutput;
  }
}
