/**
 * CreateSpecification handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: specifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createSpecification } from "@vericlause/api-server/domains/specifications/handlers";
import type { SpecificationsDDDDependencies } from "@vericlause/api-server/domains/specifications";
import { createSpecification as createSpecificationEntity } from "@vericlause/factories/specifications";
import { createCreateSpecificationRequest } from "@vericlause/factories/specifications";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@vericlause/tests/shared";
import { SPECIFICATIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateSpecification", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: SpecificationsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<SpecificationsDDDDependencies>(
      SPECIFICATIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateSpecificationRequest();
    const entity = createSpecificationEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateSpecification, "execute").mockResolvedValue(useCaseResult);

    await createSpecification(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateSpecification.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
