/**
 * GetSpecification handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: specifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getSpecification } from "@vericlause/api-server/domains/specifications/handlers";
import type { SpecificationsDDDDependencies } from "@vericlause/api-server/domains/specifications";
import { createSpecification as createSpecificationEntity } from "@vericlause/factories/specifications";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@vericlause/tests/shared";
import { SPECIFICATIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetSpecification", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: SpecificationsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<SpecificationsDDDDependencies>(
      SPECIFICATIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createSpecificationEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetSpecification, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { specId: entity.id };

    await getSpecification(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetSpecification.execute).toHaveBeenCalledWith(expect.objectContaining({ specId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { specId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetSpecification, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getSpecification(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
