/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: specifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the specifications domain.
 * Use these factories in tests to create test data.
 */

export { createCreateAcceptRequest } from "./accept/dto/create-accept.dto.factory.js";
export { createCreateSpecificationRequest } from "./specification/dto/create-specification.dto.factory.js";
export { createSpecification } from "./specification/entity/specification.entity.factory.js";
export { createUpdateSpecificationRequest } from "./specification/dto/update-specification.dto.factory.js";
