/**
 * ExecuteListFindings - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: findings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListFindings Use Case
 *
 * DDD: Application use case for list Finding.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListFindingsInput, ListFindingsOutput } from "../dto/finding.dto";
import type { ExecutionContextService, IdGeneratorService } from "@vericlause/services/_shared/index.js";
import type { FindingRepository } from "../ports";

export class ExecuteListFindings {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly finding: FindingRepository
  ) {}

  async execute(input: ListFindingsInput): Promise<ListFindingsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.fndId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.finding.listFindings({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListFindingsOutput;
  }
}
