/**
 * ExecuteCreateFinding - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: findings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateFinding Use Case
 *
 * DDD: Application use case for create Finding.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateFindingInput, CreateFindingOutput } from "../dto/finding.dto";
import type { ExecutionContextService, IdGeneratorService } from "@vericlause/services/_shared/index.js";
import type { FindingRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateFinding {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly finding: FindingRepository
  ) {}

  async execute(input: CreateFindingInput): Promise<CreateFindingOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.fndId();

    // All field names extracted from OpenAPI spec: jobId, projectId, property, severity, status, suggestedRootCause, title, trace, versionRef
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.title) {
      throw new ValidationError("title is required");
    }
    if (!input.severity) {
      throw new ValidationError("severity is required");
    }
    if (!input.projectId) {
      throw new ValidationError("projectId is required");
    }
    if (!input.jobId) {
      throw new ValidationError("jobId is required");
    }
    if (!input.versionRef) {
      throw new ValidationError("versionRef is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (findings domain)
    const entityId = this.idGenerator.fndId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.finding.createFinding({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateFindingOutput;
  }
}
