/**
 * CreateFinding DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: findings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import { ulid } from "ulid";
import type { FindingCreateRequest } from "@vericlause/core/findings";
import { findingsSchemas } from "@vericlause/core/findings";
// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "fnd";

export function createCreateFindingRequest(overrides: Partial<FindingCreateRequest> = {}) {
  const raw = {
    jobId: overrides.jobId ?? `job_${ulid().toLowerCase()}`,
    projectId: overrides.projectId ?? `prj_${ulid().toLowerCase()}`,
    severity: overrides.severity ?? "info",
    title: overrides.title ?? faker.lorem.sentence(),
    versionRef: overrides.versionRef ?? faker.lorem.word(),
    ...overrides,
  };

  return findingsSchemas.FindingCreateRequest.parse(raw);
}
