/**
 * GetFinding DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: findings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetFindingParams } from "@vericlause/core/findings";

export function createGetFindingRequest(overrides: Partial<GetFindingParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
