/**
 * Repository interface for AnalysisJob
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: analysis-jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  AnalysisJobEntity
} from "../models/analysis-job.entity.js";
import type {
  ListAnalysisJobsParams,
  AnalysisJobCreateRequest
} from "../types/index.js";
/**
 * AnalysisJobRepository Interface
 */
export interface AnalysisJobRepository extends CreateReadRepository<AnalysisJobEntity, AnalysisJobCreateRequest, string, ListAnalysisJobsParams> {

}
