/**
 * Waivers DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: waivers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Waivers Domain Module - Composition root
 *
 * DDD: Composition root for waivers domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ApproveRepositoryAdapter,
  WaiverRepositoryAdapter,
} from "@vericlause/adapters/waivers";
import { getIdGeneratorService } from "@vericlause/adapters";
import type { AdapterDynamoDBClient } from "@vericlause/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteApproveWaiver,
  ExecuteGetWaiver,
  ExecuteListWaivers,
  ExecuteProposeWaiver,
} from "@vericlause/services/waivers/usecases";
// Ports (interfaces)
import type {
  ApproveRepository,
  WaiverRepository,
} from "@vericlause/services/waivers/ports";

export interface WaiversDomainModule {
  repos: {
    approves: ApproveRepository;
    waivers: WaiverRepository;
  };
  useCases: {
    approves: {
      create: ExecuteApproveWaiver;
    };
    waivers: {
      get: ExecuteGetWaiver;
      list: ExecuteListWaivers;
    };
  };
}

export function buildWaiversDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): WaiversDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      approves?: ApproveRepository;
      waivers?: WaiverRepository;
    } = {};

    obj.approves = new ApproveRepositoryAdapter(dynamoClient);
    obj.waivers = new WaiverRepositoryAdapter(dynamoClient);
    return {
      approves: obj.approves!,
      waivers: obj.waivers!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    approves: {
      create: new ExecuteApproveWaiver(executionContext, idGenerator, repos.approves),
    },
    waivers: {
      get: new ExecuteGetWaiver(executionContext, idGenerator, repos.waivers),
      list: new ExecuteListWaivers(executionContext, idGenerator, repos.waivers),
    },
  };
  return { repos, useCases: useCases as WaiversDomainModule["useCases"] };
}
