/**
 * CreateApprove DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: waivers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { WaiverApproveRequest } from "@vericlause/core/waivers";
import { waiversSchemas } from "@vericlause/core/waivers";

export function createCreateApproveRequest(overrides: Partial<WaiverApproveRequest> = {}) {
  const raw = {
    ...overrides,
  };

  return waiversSchemas.WaiverApproveRequest.parse(raw);
}
