/**
 * Handlers for AssuranceArtefact
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AssuranceArtefactsDomainModule } from "../dependencies/assurance-artefacts-ddd.dependencies.js";
import type { AssuranceArtefactCreateRequest } from "@vericlause/core/assurance-artefacts/types";
import type { CreateAssuranceArtefactInput, GetAssuranceArtefactInput, ListAssuranceArtefactsInput } from "@vericlause/services/assurance-artefacts";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/assurance-artefacts
 * Operation: listAssuranceArtefacts
 */
export async function listAssuranceArtefacts(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], projectId?: string | string[], versionRef?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: AssuranceArtefactsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListAssuranceArtefactsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.assuranceArtefacts.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/assurance-artefacts
 * Operation: createAssuranceArtefact
 */
export async function createAssuranceArtefact(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: AssuranceArtefactCreateRequest }>,
  reply: FastifyReply,
  deps: AssuranceArtefactsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateAssuranceArtefactInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.assuranceArtefacts.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/assurance-artefacts/{artefactId}
 * Operation: getAssuranceArtefact
 */
export async function getAssuranceArtefact(
  request: FastifyRequest<{ Params: { artefactId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AssuranceArtefactsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetAssuranceArtefactInput = {
    artefactId: request.params.artefactId,
  };
  const result = await deps.useCases.assuranceArtefacts.get.execute(input);
  return reply.code(200).send(result);
}


