/**
 * AnalysisJob Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: analysis-jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { AnalysisJobEntity } from "@vericlause/core/analysis-jobs/models/index.js";
import { analysisJobsSchemas } from "@vericlause/core/analysis-jobs";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "job";

export function createAnalysisJob(overrides: Partial<AnalysisJobEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    jobId: overrides.jobId ?? `job_${ulid().toLowerCase()}`,
    jobType: overrides.jobType ?? "formalVerification",
    projectId: overrides.projectId ?? `prj_${ulid().toLowerCase()}`,
    status: overrides.status ?? "queued",
    versionRef: overrides.versionRef ?? faker.lorem.word(),
    ...overrides,
  };

  return analysisJobsSchemas.AnalysisJob.parse(raw);
}

export function analysisJobBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createAnalysisJob(overrides));
}
