/**
 * WaiverRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: waivers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * WaiverRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements WaiverRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  WaiverRepository,
} from "@vericlause/services/waivers";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { WaiverRepositoryDdb } from "./waiver-repository.ddb.js";

/**
 * WaiverRepositoryAdapter
 *
 * Implements WaiverRepository port for infrastructure layer.
 */
export class WaiverRepositoryAdapter implements WaiverRepository {
  private readonly ddb: WaiverRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new WaiverRepositoryDdb(this.dynamoClient);
  }

  async listWaivers(input: Parameters<WaiverRepository['listWaivers']>[0]): Promise<Awaited<ReturnType<WaiverRepository['listWaivers']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listWaivers(input);
  }

  async proposeWaiver(input: Parameters<WaiverRepository['proposeWaiver']>[0]): Promise<Awaited<ReturnType<WaiverRepository['proposeWaiver']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.proposeWaiver(input);
  }

  async getWaiver(input: Parameters<WaiverRepository['getWaiver']>[0]): Promise<Awaited<ReturnType<WaiverRepository['getWaiver']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getWaiver(input);
  }
}
