/**
 * Handlers for Waiver
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: waivers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { WaiversDomainModule } from "../dependencies/waivers-ddd.dependencies.js";
import type { WaiverCreateRequest } from "@vericlause/core/waivers/types";
import type { GetWaiverInput, ListWaiversInput, ProposeWaiverInput } from "@vericlause/services/waivers";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/waivers
 * Operation: listWaivers
 */
export async function listWaivers(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], findingId?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: WaiversDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListWaiversInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.waivers.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/waivers
 * Operation: proposeWaiver
 */
export async function proposeWaiver(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: WaiverCreateRequest }>,
  reply: FastifyReply,
  deps: WaiversDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ProposeWaiverInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.waivers.get.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/waivers/{waiverId}
 * Operation: getWaiver
 */
export async function getWaiver(
  request: FastifyRequest<{ Params: { waiverId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: WaiversDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetWaiverInput = {
    waiverId: request.params.waiverId,
  };
  const result = await deps.useCases.waivers.get.execute(input);
  return reply.code(200).send(result);
}


