/**
 * ReleaseGates Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: release-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const evaluateReleaseGate_Body = z
  .object({
    projectId: z.string().regex(/^prj_[0-9A-HJKMNP-TV-Z]{26}$/),
    versionRef: z.string().min(1),
    decision: z.enum(['allow', 'block']).optional(),
    status: z.enum(['pending', 'final']).optional(),
    rationale: z.string().optional(),
  })
  .passthrough();

export const schemas: any = {
  evaluateReleaseGate_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/release-gates',
    alias: 'listReleaseGates',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().min(1).max(512).optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(100).optional().default(25),
      },
      {
        name: 'projectId',
        type: 'Query',
        schema: z
          .string()
          .regex(/^prj_[0-9A-HJKMNP-TV-Z]{26}$/)
          .optional(),
      },
      {
        name: 'versionRef',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'decision',
        type: 'Query',
        schema: z.enum(['allow', 'block']).optional(),
      },
      {
        name: 'status',
        type: 'Query',
        schema: z.enum(['pending', 'final']).optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  gateId: z.string().regex(/^gat_[0-9A-HJKMNP-TV-Z]{26}$/),
                  projectId: z.string().regex(/^prj_[0-9A-HJKMNP-TV-Z]{26}$/),
                  versionRef: z.string().min(1),
                  decision: z.enum(['allow', 'block']),
                  status: z.enum(['pending', 'final']),
                  openCriticalCount: z.number().int().gte(0),
                  artefactId: z
                    .string()
                    .regex(/^art_[0-9A-HJKMNP-TV-Z]{26}$/)
                    .optional(),
                  rationale: z.string().optional(),
                  createdAt: z.string().datetime({ offset: true }),
                  updatedAt: z.string().datetime({ offset: true }),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/release-gates',
    alias: 'evaluateReleaseGate',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: evaluateReleaseGate_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            gateId: z.string().regex(/^gat_[0-9A-HJKMNP-TV-Z]{26}$/),
            projectId: z.string().regex(/^prj_[0-9A-HJKMNP-TV-Z]{26}$/),
            versionRef: z.string().min(1),
            decision: z.enum(['allow', 'block']),
            status: z.enum(['pending', 'final']),
            openCriticalCount: z.number().int().gte(0),
            artefactId: z
              .string()
              .regex(/^art_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            rationale: z.string().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/release-gates/:gateId',
    alias: 'getReleaseGate',
    requestFormat: 'json',
    parameters: [
      {
        name: 'gateId',
        type: 'Path',
        schema: z.string().regex(/^gat_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            gateId: z.string().regex(/^gat_[0-9A-HJKMNP-TV-Z]{26}$/),
            projectId: z.string().regex(/^prj_[0-9A-HJKMNP-TV-Z]{26}$/),
            versionRef: z.string().min(1),
            decision: z.enum(['allow', 'block']),
            status: z.enum(['pending', 'final']),
            openCriticalCount: z.number().int().gte(0),
            artefactId: z
              .string()
              .regex(/^art_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            rationale: z.string().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
