/**
 * Domain routes – register all domain route modules.
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Rescans platform/api-server/src/domains and includes only domains that have
 * routes/index.ts and dependencies/{domain}-ddd.dependencies.ts.
 * Extension excludes/imports from x-codegen.api-server.extensions in OpenAPI YAML.
 */

import type { FastifyInstance } from "fastify";
import { registerDomainFromModule } from "./route-registration.js";

// Static imports so the bundle includes all domain route modules
import * as analysisJobsRoutes from "../../domains/analysis-jobs/routes/index.js";
import * as assuranceArtefactsRoutes from "../../domains/assurance-artefacts/routes/index.js";
import * as contractProjectsRoutes from "../../domains/contract-projects/routes/index.js";
import * as findingsRoutes from "../../domains/findings/routes/index.js";
import * as identityRoutes from "../../domains/identity/routes/index.js";
import * as releaseGatesRoutes from "../../domains/release-gates/routes/index.js";
import * as specificationsRoutes from "../../domains/specifications/routes/index.js";
import * as waiversRoutes from "../../domains/waivers/routes/index.js";

const DOMAIN_MODULES: Array<{
  domain: string;
  mod: Record<string, unknown>;
  exclude?: string[];
}> = [
  { domain: "analysis-jobs", mod: analysisJobsRoutes },
  { domain: "assurance-artefacts", mod: assuranceArtefactsRoutes },
  { domain: "contract-projects", mod: contractProjectsRoutes },
  { domain: "findings", mod: findingsRoutes },
  {
    domain: "identity", mod: identityRoutes,
    exclude: ["authRoutes", "loginRoutes", "logoutRoutes", "signupRoutes", "sessionRoutes", "refreshRoutes", "tokenRoutes", "profileRoutes"],
  },
  { domain: "release-gates", mod: releaseGatesRoutes },
  { domain: "specifications", mod: specificationsRoutes },
  { domain: "waivers", mod: waiversRoutes },
];

export async function registerAllDomainRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  console.log("[DEBUG] Registering domain routes...");
  try {
    for (const { domain, mod, exclude } of DOMAIN_MODULES) {
      await registerDomainFromModule(fastify, domain, mod, exclude ?? []);
    }
    console.log("[DEBUG] ✅ All domain routes registered");
  } catch (error: unknown) {
    const err = error instanceof Error ? error : new Error(String(error));
    console.error("[DEBUG] ❌ Error registering domain routes:", err.message);
    if (err.stack) console.error(err.stack);
    throw error;
  }
}
