/**
 * CreateAnalysisJob DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: analysis-jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import { ulid } from "ulid";
import type { AnalysisJobCreateRequest } from "@vericlause/core/analysis-jobs";
import { analysisJobsSchemas } from "@vericlause/core/analysis-jobs";
// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "job";

export function createCreateAnalysisJobRequest(overrides: Partial<AnalysisJobCreateRequest> = {}) {
  const raw = {
    jobType: overrides.jobType ?? "formalVerification",
    projectId: overrides.projectId ?? `prj_${ulid().toLowerCase()}`,
    versionRef: overrides.versionRef ?? faker.lorem.word(),
    ...overrides,
  };

  return analysisJobsSchemas.AnalysisJobCreateRequest.parse(raw);
}
