/**
 * Routes for AnalysisJob
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: analysis-jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createAnalysisJob, getAnalysisJob, listAnalysisJobs } from "../handlers/analysis-job.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { AnalysisJobCreateRequest } from "@vericlause/core/analysis-jobs/types";

// Fastify types are available globally
export async function analysisJobRoutes(fastify: FastifyInstance) {
  // POST /v1/analysis-jobs (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/analysis-jobs",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: AnalysisJobCreateRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAnalysisJobsDependenciesForRequest();
        await createAnalysisJob(request, reply, deps);
      });
    }
  );


  // GET /v1/analysis-jobs (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/analysis-jobs",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAnalysisJobsDependenciesForRequest();
        await listAnalysisJobs(request, reply, deps);
      });
    }
  );


  // GET /v1/analysis-jobs/{jobId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/analysis-jobs/:jobId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { jobId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAnalysisJobsDependenciesForRequest();
        await getAnalysisJob(request, reply, deps);
      });
    }
  );


}
