apis:
  identity:
    root: src/identity.yaml
  contract-projects:
    root: src/contract-projects.yaml
  specifications:
    root: src/specifications.yaml
  analysis-jobs:
    root: src/analysis-jobs.yaml
  findings:
    root: src/findings.yaml
  waivers:
    root: src/waivers.yaml
  release-gates:
    root: src/release-gates.yaml
  assurance-artefacts:
    root: src/assurance-artefacts.yaml

extends:
  - recommended

rules:
  no-unused-components: off
  operation-4xx-response: warn
  info-license: off
  info-license-url: off
  tag-description: off
  operation-operationId: error
  no-invalid-media-type-examples: off

theme:
  openapi:
    generateCodeSamples:
      languages: []
