/**
 * Waiver DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: waivers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Waiver DTOs
 *
 * DDD: Application DTOs for Waiver use cases.
 */

import type { GetWaiverParams, ListWaiversParams, WaiverCreateRequest } from "@vericlause/core/waivers/types";

export type ListWaiversInput = ListWaiversParams;

export type ProposeWaiverInput = WaiverCreateRequest;

export type GetWaiverInput = GetWaiverParams;

export type ListWaiversOutput = {};

export type ProposeWaiverOutput = {};

export type GetWaiverOutput = {};
