/**
 * AnalysisJobRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: analysis-jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AnalysisJobRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AnalysisJobRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AnalysisJobRepository,
} from "@vericlause/services/analysis-jobs";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AnalysisJobRepositoryDdb } from "./analysis-job-repository.ddb.js";

/**
 * AnalysisJobRepositoryAdapter
 *
 * Implements AnalysisJobRepository port for infrastructure layer.
 */
export class AnalysisJobRepositoryAdapter implements AnalysisJobRepository {
  private readonly ddb: AnalysisJobRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AnalysisJobRepositoryDdb(this.dynamoClient);
  }

  async listAnalysisJobs(input: Parameters<AnalysisJobRepository['listAnalysisJobs']>[0]): Promise<Awaited<ReturnType<AnalysisJobRepository['listAnalysisJobs']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listAnalysisJobs(input);
  }

  async createAnalysisJob(input: Parameters<AnalysisJobRepository['createAnalysisJob']>[0]): Promise<Awaited<ReturnType<AnalysisJobRepository['createAnalysisJob']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createAnalysisJob(input);
  }

  async getAnalysisJob(input: Parameters<AnalysisJobRepository['getAnalysisJob']>[0]): Promise<Awaited<ReturnType<AnalysisJobRepository['getAnalysisJob']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getAnalysisJob(input);
  }
}
