/**
 * ContractProject Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contract-projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ContractProjectEntity } from "@vericlause/core/contract-projects/models/index.js";
import { contractProjectsSchemas } from "@vericlause/core/contract-projects";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "prj";

export function createContractProject(overrides: Partial<ContractProjectEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    language: overrides.language ?? "solidity",
    name: overrides.name ?? faker.person.fullName(),
    openCriticalCount: overrides.openCriticalCount ?? faker.number.int({ min: 1, max: 100 }),
    privateMode: overrides.privateMode ?? faker.datatype.boolean(),
    projectId: overrides.projectId ?? `prj_${ulid().toLowerCase()}`,
    status: overrides.status ?? "active",
    ...overrides,
  };

  return contractProjectsSchemas.ContractProject.parse(raw);
}

export function contractProjectBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createContractProject(overrides));
}
