/**
 * ReleaseGate DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: release-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReleaseGate DTOs
 *
 * DDD: Application DTOs for ReleaseGate use cases.
 */

import type { GetReleaseGateParams, ListReleaseGatesParams, ReleaseGateCreateRequest } from "@vericlause/core/release-gates/types";

export type ListReleaseGatesInput = ListReleaseGatesParams;

export type EvaluateReleaseGateInput = ReleaseGateCreateRequest;

export type GetReleaseGateInput = GetReleaseGateParams;

export type ListReleaseGatesOutput = {};

export type EvaluateReleaseGateOutput = {};

export type GetReleaseGateOutput = {};
