/**
 * ContractProject DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contract-projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ContractProject DTOs
 *
 * DDD: Application DTOs for ContractProject use cases.
 */

import type { ContractProjectCreateRequest, ContractProjectUpdateRequest, GetContractProjectParams, ListContractProjectsParams, UpdateContractProjectParams } from "@vericlause/core/contract-projects/types";

export type ListContractProjectsInput = ListContractProjectsParams;

export type CreateContractProjectInput = ContractProjectCreateRequest;

export type GetContractProjectInput = GetContractProjectParams;

export type UpdateContractProjectInput = UpdateContractProjectParams & ContractProjectUpdateRequest;

export type ListContractProjectsOutput = {};

export type CreateContractProjectOutput = {};

export type GetContractProjectOutput = {};

export type UpdateContractProjectOutput = {};
