/**
 * Version DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contract-projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Version DTOs
 *
 * DDD: Application DTOs for Version use cases.
 */

import type { ContractVersionCreateRequest, CreateContractVersionParams, GetContractVersionParams, ListContractVersionsParams } from "@vericlause/core/contract-projects/types";

export type ListContractVersionsInput = ListContractVersionsParams;

export type CreateContractVersionInput = CreateContractVersionParams & ContractVersionCreateRequest;

export type GetContractVersionInput = GetContractVersionParams;

export type ListContractVersionsOutput = {};

export type CreateContractVersionOutput = {};

export type GetContractVersionOutput = {};
