/**
 * ExecuteGetContractProject - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contract-projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetContractProject Use Case
 *
 * DDD: Application use case for get ContractProject.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetContractProjectInput, GetContractProjectOutput } from "../dto/contract-project.dto";
import type { ExecutionContextService, IdGeneratorService } from "@vericlause/services/_shared/index.js";
import type { ContractProjectRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetContractProject {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly contractProject: ContractProjectRepository
  ) {}

  async execute(input: GetContractProjectInput): Promise<GetContractProjectOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prjId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).projectId) {
      throw new ValidationError("projectId is required");
    }
    const projectId = (input as any).projectId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.contractProject.getContractProject({ projectId: projectId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${projectId}`);
    }

    return entity as GetContractProjectOutput;
  }
}
