/**
 * ReleaseGates DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: release-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReleaseGates Domain Module - Composition root
 *
 * DDD: Composition root for release-gates domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ReleaseGateRepositoryAdapter,
} from "@vericlause/adapters/release-gates";
import { getIdGeneratorService } from "@vericlause/adapters";
import type { AdapterDynamoDBClient } from "@vericlause/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteEvaluateReleaseGate,
  ExecuteGetReleaseGate,
  ExecuteListReleaseGates,
} from "@vericlause/services/release-gates/usecases";
// Ports (interfaces)
import type {
  ReleaseGateRepository,
} from "@vericlause/services/release-gates/ports";

export interface ReleaseGatesDomainModule {
  repos: {
    releaseGates: ReleaseGateRepository;
  };
  useCases: {
    releaseGates: {
      create: ExecuteEvaluateReleaseGate;
      get: ExecuteGetReleaseGate;
      list: ExecuteListReleaseGates;
    };
  };
}

export function buildReleaseGatesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ReleaseGatesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      releaseGates?: ReleaseGateRepository;
    } = {};

    obj.releaseGates = new ReleaseGateRepositoryAdapter(dynamoClient);
    return {
      releaseGates: obj.releaseGates!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    releaseGates: {
      create: new ExecuteEvaluateReleaseGate(executionContext, idGenerator, repos.releaseGates),
      get: new ExecuteGetReleaseGate(executionContext, idGenerator, repos.releaseGates),
      list: new ExecuteListReleaseGates(executionContext, idGenerator, repos.releaseGates),
    },
  };
  return { repos, useCases: useCases as ReleaseGatesDomainModule["useCases"] };
}
