/**
 * Specifications Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: specifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const createSpecification_Body = z
  .object({
    projectId: z.string().regex(/^prj_[0-9A-HJKMNP-TV-Z]{26}$/),
    versionRef: z.string().min(1),
    kind: z.enum(['invariant', 'accessControl', 'valueFlow']),
    title: z.string().min(1),
    body: z.string().optional(),
    requiredForGate: z.boolean().optional().default(false),
    historicalTemplate: z
      .enum(['reentrancy', 'uncheckedCall', 'custodyBug', 'custom'])
      .optional(),
    status: z.enum(['draft', 'accepted', 'required', 'inferred']).optional(),
  })
  .passthrough();
const updateSpecification_Body = z
  .object({
    title: z.string().min(1),
    body: z.string(),
    requiredForGate: z.boolean(),
    status: z.enum(['draft', 'accepted', 'required', 'inferred']),
    historicalTemplate: z.enum([
      'reentrancy',
      'uncheckedCall',
      'custodyBug',
      'custom',
    ]),
  })
  .partial()
  .passthrough();

export const schemas: any = {
  createSpecification_Body,
  updateSpecification_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/specifications',
    alias: 'listSpecifications',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().min(1).max(512).optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(100).optional().default(25),
      },
      {
        name: 'projectId',
        type: 'Query',
        schema: z
          .string()
          .regex(/^prj_[0-9A-HJKMNP-TV-Z]{26}$/)
          .optional(),
      },
      {
        name: 'versionRef',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'status',
        type: 'Query',
        schema: z
          .enum(['draft', 'accepted', 'required', 'inferred'])
          .optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  specId: z.string().regex(/^spc_[0-9A-HJKMNP-TV-Z]{26}$/),
                  projectId: z.string().regex(/^prj_[0-9A-HJKMNP-TV-Z]{26}$/),
                  versionRef: z.string().min(1),
                  kind: z.enum(['invariant', 'accessControl', 'valueFlow']),
                  title: z.string().min(1),
                  body: z.string().optional(),
                  status: z.enum(['draft', 'accepted', 'required', 'inferred']),
                  requiredForGate: z.boolean(),
                  historicalTemplate: z
                    .enum([
                      'reentrancy',
                      'uncheckedCall',
                      'custodyBug',
                      'custom',
                    ])
                    .optional(),
                  inferredFromTrace: z.boolean().optional(),
                  createdAt: z.string().datetime({ offset: true }),
                  updatedAt: z.string().datetime({ offset: true }),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/specifications',
    alias: 'createSpecification',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: createSpecification_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            specId: z.string().regex(/^spc_[0-9A-HJKMNP-TV-Z]{26}$/),
            projectId: z.string().regex(/^prj_[0-9A-HJKMNP-TV-Z]{26}$/),
            versionRef: z.string().min(1),
            kind: z.enum(['invariant', 'accessControl', 'valueFlow']),
            title: z.string().min(1),
            body: z.string().optional(),
            status: z.enum(['draft', 'accepted', 'required', 'inferred']),
            requiredForGate: z.boolean(),
            historicalTemplate: z
              .enum(['reentrancy', 'uncheckedCall', 'custodyBug', 'custom'])
              .optional(),
            inferredFromTrace: z.boolean().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/specifications/:specId',
    alias: 'getSpecification',
    requestFormat: 'json',
    parameters: [
      {
        name: 'specId',
        type: 'Path',
        schema: z.string().regex(/^spc_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            specId: z.string().regex(/^spc_[0-9A-HJKMNP-TV-Z]{26}$/),
            projectId: z.string().regex(/^prj_[0-9A-HJKMNP-TV-Z]{26}$/),
            versionRef: z.string().min(1),
            kind: z.enum(['invariant', 'accessControl', 'valueFlow']),
            title: z.string().min(1),
            body: z.string().optional(),
            status: z.enum(['draft', 'accepted', 'required', 'inferred']),
            requiredForGate: z.boolean(),
            historicalTemplate: z
              .enum(['reentrancy', 'uncheckedCall', 'custodyBug', 'custom'])
              .optional(),
            inferredFromTrace: z.boolean().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'patch',
    path: '/v1/specifications/:specId',
    alias: 'updateSpecification',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: updateSpecification_Body,
      },
      {
        name: 'specId',
        type: 'Path',
        schema: z.string().regex(/^spc_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            specId: z.string().regex(/^spc_[0-9A-HJKMNP-TV-Z]{26}$/),
            projectId: z.string().regex(/^prj_[0-9A-HJKMNP-TV-Z]{26}$/),
            versionRef: z.string().min(1),
            kind: z.enum(['invariant', 'accessControl', 'valueFlow']),
            title: z.string().min(1),
            body: z.string().optional(),
            status: z.enum(['draft', 'accepted', 'required', 'inferred']),
            requiredForGate: z.boolean(),
            historicalTemplate: z
              .enum(['reentrancy', 'uncheckedCall', 'custodyBug', 'custom'])
              .optional(),
            inferredFromTrace: z.boolean().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 400,
        description: `Malformed request`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/specifications/:specId/accept',
    alias: 'acceptInferredSpecification',
    requestFormat: 'json',
    parameters: [
      {
        name: 'specId',
        type: 'Path',
        schema: z.string().regex(/^spc_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            specId: z.string().regex(/^spc_[0-9A-HJKMNP-TV-Z]{26}$/),
            projectId: z.string().regex(/^prj_[0-9A-HJKMNP-TV-Z]{26}$/),
            versionRef: z.string().min(1),
            kind: z.enum(['invariant', 'accessControl', 'valueFlow']),
            title: z.string().min(1),
            body: z.string().optional(),
            status: z.enum(['draft', 'accepted', 'required', 'inferred']),
            requiredForGate: z.boolean(),
            historicalTemplate: z
              .enum(['reentrancy', 'uncheckedCall', 'custodyBug', 'custom'])
              .optional(),
            inferredFromTrace: z.boolean().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 409,
        description: `Idempotency key reuse with different body, or state conflict`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
