/**
 * Routes for ContractProject
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contract-projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createContractProject, getContractProject, listContractProjects, updateContractProject } from "../handlers/contract-project.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { ContractProjectCreateRequest, ContractProjectUpdateRequest } from "@vericlause/core/contract-projects/types";

// Fastify types are available globally
export async function contractProjectRoutes(fastify: FastifyInstance) {
  // POST /v1/contract-projects (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/contract-projects",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: ContractProjectCreateRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getContractProjectsDependenciesForRequest();
        await createContractProject(request, reply, deps);
      });
    }
  );


  // GET /v1/contract-projects (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/contract-projects",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getContractProjectsDependenciesForRequest();
        await listContractProjects(request, reply, deps);
      });
    }
  );


  // GET /v1/contract-projects/{projectId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/contract-projects/:projectId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { projectId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getContractProjectsDependenciesForRequest();
        await getContractProject(request, reply, deps);
      });
    }
  );


  // PATCH /v1/contract-projects/{projectId} (unscoped; scope set for security middleware)
  fastify.patch(
    "/v1/contract-projects/:projectId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { projectId: string }; Querystring: Record<string, string | string[] | undefined>; Body: ContractProjectUpdateRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getContractProjectsDependenciesForRequest();
        await updateContractProject(request, reply, deps);
      });
    }
  );


}
