/**
 * Routes for Version
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contract-projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createContractVersion, getContractVersion, listContractVersions } from "../handlers/version.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { ContractVersionCreateRequest } from "@vericlause/core/contract-projects/types";

// Fastify types are available globally
export async function versionRoutes(fastify: FastifyInstance) {
  // POST /v1/contract-projects/{projectId}/versions (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/contract-projects/:projectId/versions",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { projectId: string }; Querystring: Record<string, string | string[] | undefined>; Body: ContractVersionCreateRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getContractProjectsDependenciesForRequest();
        await createContractVersion(request, reply, deps);
      });
    }
  );


  // GET /v1/contract-projects/{projectId}/versions (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/contract-projects/:projectId/versions",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { projectId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getContractProjectsDependenciesForRequest();
        await listContractVersions(request, reply, deps);
      });
    }
  );


  // GET /v1/contract-projects/{projectId}/versions/{versionId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/contract-projects/:projectId/versions/:versionId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { projectId: string, versionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getContractProjectsDependenciesForRequest();
        await getContractVersion(request, reply, deps);
      });
    }
  );


}
