/**
 * CreateFinding handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: findings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createFinding } from "@vericlause/api-server/domains/findings/handlers";
import type { FindingsDDDDependencies } from "@vericlause/api-server/domains/findings";
import { createFinding as createFindingEntity } from "@vericlause/factories/findings";
import { createCreateFindingRequest } from "@vericlause/factories/findings";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@vericlause/tests/shared";
import { FINDINGS_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateFinding", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: FindingsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<FindingsDDDDependencies>(
      FINDINGS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateFindingRequest();
    const entity = createFindingEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateFinding, "execute").mockResolvedValue(useCaseResult);

    await createFinding(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateFinding.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
