/**
 * GetFinding handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: findings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getFinding } from "@vericlause/api-server/domains/findings/handlers";
import type { FindingsDDDDependencies } from "@vericlause/api-server/domains/findings";
import { createFinding as createFindingEntity } from "@vericlause/factories/findings";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@vericlause/tests/shared";
import { FINDINGS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetFinding", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: FindingsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<FindingsDDDDependencies>(
      FINDINGS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createFindingEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetFinding, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { findingId: entity.id };

    await getFinding(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetFinding.execute).toHaveBeenCalledWith(expect.objectContaining({ findingId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { findingId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetFinding, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getFinding(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
