/**
 * CreateSign DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { SignAssuranceArtefactParams } from "@vericlause/core/assurance-artefacts";

export function createCreateSignRequest(overrides: Partial<SignAssuranceArtefactParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
