/**
 * AssuranceArtefactRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AssuranceArtefactRepository Port
 *
 * DDD: Application port for assuranceartefactrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateAssuranceArtefactInput, CreateAssuranceArtefactOutput, GetAssuranceArtefactInput, GetAssuranceArtefactOutput, ListAssuranceArtefactsInput, ListAssuranceArtefactsOutput } from "../dto/assurance-artefact.dto";
export interface AssuranceArtefactRepository {
  listAssuranceArtefacts(input: ListAssuranceArtefactsInput): Promise<ListAssuranceArtefactsOutput>;
  createAssuranceArtefact(input: CreateAssuranceArtefactInput): Promise<CreateAssuranceArtefactOutput>;
  getAssuranceArtefact(input: GetAssuranceArtefactInput): Promise<GetAssuranceArtefactOutput>;
}

export type { CreateAssuranceArtefactInput, CreateAssuranceArtefactOutput, GetAssuranceArtefactInput, GetAssuranceArtefactOutput, ListAssuranceArtefactsInput, ListAssuranceArtefactsOutput } from "../dto/assurance-artefact.dto";
