/**
 * AuditorExportRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AuditorExportRepository Port
 *
 * DDD: Application port for auditorexportrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateAuditorExportPackInput, CreateAuditorExportPackOutput } from "../dto/auditor-export.dto";
export interface AuditorExportRepository {
  createAuditorExportPack(input: CreateAuditorExportPackInput): Promise<CreateAuditorExportPackOutput>;
}

export type { CreateAuditorExportPackInput, CreateAuditorExportPackOutput } from "../dto/auditor-export.dto";
