/**
 * CreateAssuranceArtefact DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import { ulid } from "ulid";
import type { AssuranceArtefactCreateRequest } from "@vericlause/core/assurance-artefacts";
import { assuranceArtefactsSchemas } from "@vericlause/core/assurance-artefacts";
// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "art";

export function createCreateAssuranceArtefactRequest(overrides: Partial<AssuranceArtefactCreateRequest> = {}) {
  const raw = {
    projectId: overrides.projectId ?? `prj_${ulid().toLowerCase()}`,
    versionRef: overrides.versionRef ?? faker.lorem.word(),
    ...overrides,
  };

  return assuranceArtefactsSchemas.AssuranceArtefactCreateRequest.parse(raw);
}
