/**
 * GetAssuranceArtefact DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetAssuranceArtefactParams } from "@vericlause/core/assurance-artefacts";

export function createGetAssuranceArtefactRequest(overrides: Partial<GetAssuranceArtefactParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
