/**
 * AssuranceArtefact Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { AssuranceArtefactEntity } from "@vericlause/core/assurance-artefacts/models/index.js";
import { assuranceArtefactsSchemas } from "@vericlause/core/assurance-artefacts";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "art";

export function createAssuranceArtefact(overrides: Partial<AssuranceArtefactEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    artefactId: overrides.artefactId ?? `art_${ulid().toLowerCase()}`,
    projectId: overrides.projectId ?? `prj_${ulid().toLowerCase()}`,
    status: overrides.status ?? "draft",
    versionRef: overrides.versionRef ?? faker.lorem.word(),
    ...overrides,
  };

  return assuranceArtefactsSchemas.AssuranceArtefact.parse(raw);
}

export function assuranceArtefactBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createAssuranceArtefact(overrides));
}
