/**
 * ReleaseGateRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: release-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReleaseGateRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ReleaseGateRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ReleaseGateRepository,
} from "@vericlause/services/release-gates";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ReleaseGateRepositoryDdb } from "./release-gate-repository.ddb.js";

/**
 * ReleaseGateRepositoryAdapter
 *
 * Implements ReleaseGateRepository port for infrastructure layer.
 */
export class ReleaseGateRepositoryAdapter implements ReleaseGateRepository {
  private readonly ddb: ReleaseGateRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ReleaseGateRepositoryDdb(this.dynamoClient);
  }

  async listReleaseGates(input: Parameters<ReleaseGateRepository['listReleaseGates']>[0]): Promise<Awaited<ReturnType<ReleaseGateRepository['listReleaseGates']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listReleaseGates(input);
  }

  async evaluateReleaseGate(input: Parameters<ReleaseGateRepository['evaluateReleaseGate']>[0]): Promise<Awaited<ReturnType<ReleaseGateRepository['evaluateReleaseGate']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.evaluateReleaseGate(input);
  }

  async getReleaseGate(input: Parameters<ReleaseGateRepository['getReleaseGate']>[0]): Promise<Awaited<ReturnType<ReleaseGateRepository['getReleaseGate']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getReleaseGate(input);
  }
}
