/**
 * ExecuteListWaivers - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: waivers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListWaivers Use Case
 *
 * DDD: Application use case for list Waiver.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListWaiversInput, ListWaiversOutput } from "../dto/waiver.dto";
import type { ExecutionContextService, IdGeneratorService } from "@vericlause/services/_shared/index.js";
import type { WaiverRepository } from "../ports";

export class ExecuteListWaivers {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly waiver: WaiverRepository
  ) {}

  async execute(input: ListWaiversInput): Promise<ListWaiversOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.wvrId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.waiver.listWaivers({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListWaiversOutput;
  }
}
