/**
 * ExecuteProposeWaiver - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: waivers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteProposeWaiver Use Case
 *
 * DDD: Application use case for get Waiver.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ProposeWaiverInput, ProposeWaiverOutput } from "../dto/waiver.dto";
import type { ExecutionContextService, IdGeneratorService } from "@vericlause/services/_shared/index.js";
import type { WaiverRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteProposeWaiver {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly waiver: WaiverRepository
  ) {}

  async execute(input: ProposeWaiverInput): Promise<ProposeWaiverOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.wvrId();

    // All field names extracted from OpenAPI spec: expiresAt, findingId, justification, requiredApprovals
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).findingId) {
      throw new ValidationError("findingId is required");
    }
    const findingId = (input as any).findingId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.waiver.proposeWaiver({ findingId: findingId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${findingId}`);
    }

    return entity as ProposeWaiverOutput;
  }
}
