/**
 * AssuranceArtefact Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/assurance-artefacts.openapi.types.js";
import { schemas } from "../schemas/assurance-artefacts.schemas.js";

/**
 * Entity: AssuranceArtefactEntity
 * Description: Represents the AssuranceArtefact domain model.
 * Source: schemas.AssuranceArtefact
 * Type: Domain Entity (API)
 */
export const AssuranceArtefactEntitySchema = schemas.AssuranceArtefact;
export type AssuranceArtefactEntity = components["schemas"]["AssuranceArtefact"];
