/**
 * FindingRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: findings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FindingRepository Port
 *
 * DDD: Application port for findingrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateFindingInput, CreateFindingOutput, GetFindingInput, GetFindingOutput, ListFindingsInput, ListFindingsOutput } from "../dto/finding.dto";
export interface FindingRepository {
  listFindings(input: ListFindingsInput): Promise<ListFindingsOutput>;
  createFinding(input: CreateFindingInput): Promise<CreateFindingOutput>;
  getFinding(input: GetFindingInput): Promise<GetFindingOutput>;
}

export type { CreateFindingInput, CreateFindingOutput, GetFindingInput, GetFindingOutput, ListFindingsInput, ListFindingsOutput } from "../dto/finding.dto";
