/**
 * Waiver Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: waivers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/waivers.openapi.types.js";
import { schemas } from "../schemas/waivers.schemas.js";

/**
 * Entity: WaiverEntity
 * Description: Represents the Waiver domain model.
 * Source: schemas.Waiver
 * Type: Domain Entity (API)
 */
export const WaiverEntitySchema = schemas.Waiver;
export type WaiverEntity = components["schemas"]["Waiver"];
