/**
 * GetReleaseGate handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: release-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getReleaseGate } from "@vericlause/api-server/domains/release-gates/handlers";
import type { ReleaseGatesDDDDependencies } from "@vericlause/api-server/domains/release-gates";
import { createReleaseGate as createReleaseGateEntity } from "@vericlause/factories/release-gates";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@vericlause/tests/shared";
import { RELEASEGATES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetReleaseGate", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ReleaseGatesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ReleaseGatesDDDDependencies>(
      RELEASEGATES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createReleaseGateEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetReleaseGate, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { gateId: entity.id };

    await getReleaseGate(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetReleaseGate.execute).toHaveBeenCalledWith(expect.objectContaining({ gateId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { gateId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetReleaseGate, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getReleaseGate(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
