/**
 * CreateSpecification DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: specifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import { ulid } from "ulid";
import type { SpecificationCreateRequest } from "@vericlause/core/specifications";
import { specificationsSchemas } from "@vericlause/core/specifications";
// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "spc";

export function createCreateSpecificationRequest(overrides: Partial<SpecificationCreateRequest> = {}) {
  const raw = {
    kind: overrides.kind ?? "invariant",
    projectId: overrides.projectId ?? `prj_${ulid().toLowerCase()}`,
    title: overrides.title ?? faker.lorem.sentence(),
    versionRef: overrides.versionRef ?? faker.lorem.word(),
    ...overrides,
  };

  return specificationsSchemas.SpecificationCreateRequest.parse(raw);
}
