/**
 * AssuranceArtefactRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AssuranceArtefactRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AssuranceArtefactRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AssuranceArtefactRepository,
} from "@vericlause/services/assurance-artefacts";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AssuranceArtefactRepositoryDdb } from "./assurance-artefact-repository.ddb.js";

/**
 * AssuranceArtefactRepositoryAdapter
 *
 * Implements AssuranceArtefactRepository port for infrastructure layer.
 */
export class AssuranceArtefactRepositoryAdapter implements AssuranceArtefactRepository {
  private readonly ddb: AssuranceArtefactRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AssuranceArtefactRepositoryDdb(this.dynamoClient);
  }

  async listAssuranceArtefacts(input: Parameters<AssuranceArtefactRepository['listAssuranceArtefacts']>[0]): Promise<Awaited<ReturnType<AssuranceArtefactRepository['listAssuranceArtefacts']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listAssuranceArtefacts(input);
  }

  async createAssuranceArtefact(input: Parameters<AssuranceArtefactRepository['createAssuranceArtefact']>[0]): Promise<Awaited<ReturnType<AssuranceArtefactRepository['createAssuranceArtefact']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createAssuranceArtefact(input);
  }

  async getAssuranceArtefact(input: Parameters<AssuranceArtefactRepository['getAssuranceArtefact']>[0]): Promise<Awaited<ReturnType<AssuranceArtefactRepository['getAssuranceArtefact']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getAssuranceArtefact(input);
  }
}
