/**
 * AuditorExportRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AuditorExportRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AuditorExportRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AuditorExportRepository,
} from "@vericlause/services/assurance-artefacts";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AuditorExportRepositoryDdb } from "./auditor-export-repository.ddb.js";

/**
 * AuditorExportRepositoryAdapter
 *
 * Implements AuditorExportRepository port for infrastructure layer.
 */
export class AuditorExportRepositoryAdapter implements AuditorExportRepository {
  private readonly ddb: AuditorExportRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AuditorExportRepositoryDdb(this.dynamoClient);
  }

  async createAuditorExportPack(input: Parameters<AuditorExportRepository['createAuditorExportPack']>[0]): Promise<Awaited<ReturnType<AuditorExportRepository['createAuditorExportPack']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createAuditorExportPack(input);
  }
}
