/**
 * AcceptRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: specifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AcceptRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AcceptRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AcceptRepository,
} from "@vericlause/services/specifications";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AcceptRepositoryDdb } from "./accept-repository.ddb.js";

/**
 * AcceptRepositoryAdapter
 *
 * Implements AcceptRepository port for infrastructure layer.
 */
export class AcceptRepositoryAdapter implements AcceptRepository {
  private readonly ddb: AcceptRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AcceptRepositoryDdb(this.dynamoClient);
  }

  async acceptInferredSpecification(input: Parameters<AcceptRepository['acceptInferredSpecification']>[0]): Promise<Awaited<ReturnType<AcceptRepository['acceptInferredSpecification']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.acceptInferredSpecification(input);
  }
}
