/**
 * CreateContractProject DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contract-projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ContractProjectCreateRequest } from "@vericlause/core/contract-projects";
import { contractProjectsSchemas } from "@vericlause/core/contract-projects";

export function createCreateContractProjectRequest(overrides: Partial<ContractProjectCreateRequest> = {}) {
  const raw = {
    language: overrides.language ?? "solidity",
    name: overrides.name ?? faker.person.fullName(),
    ...overrides,
  };

  return contractProjectsSchemas.ContractProjectCreateRequest.parse(raw);
}
