/**
 * UpdateContractProject DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contract-projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ContractProjectUpdateRequest } from "@vericlause/core/contract-projects";
import { contractProjectsSchemas } from "@vericlause/core/contract-projects";

export function createUpdateContractProjectRequest(overrides: Partial<ContractProjectUpdateRequest> = {}) {
  const raw = {
    ...overrides,
  };

  return contractProjectsSchemas.ContractProjectUpdateRequest.parse(raw);
}
