/**
 * CreateContractVersion handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contract-projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createContractVersion } from "@vericlause/api-server/domains/contract-projects/handlers";
import type { ContractProjectsDDDDependencies } from "@vericlause/api-server/domains/contract-projects";
import { createCreateVersionRequest } from "@vericlause/factories/contract-projects";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@vericlause/tests/shared";
import { CONTRACTPROJECTS_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateContractVersion", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ContractProjectsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ContractProjectsDDDDependencies>(
      CONTRACTPROJECTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateVersionRequest();
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateContractVersion, "execute").mockResolvedValue(useCaseResult);

    await createContractVersion(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateContractVersion.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
