/**
 * Routes for AssuranceArtefact
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createAssuranceArtefact, getAssuranceArtefact, listAssuranceArtefacts } from "../handlers/assurance-artefact.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";
import type { AssuranceArtefactCreateRequest } from "@vericlause/core/assurance-artefacts/types";

// Fastify types are available globally
export async function assuranceArtefactRoutes(fastify: FastifyInstance) {
  // POST /v1/assurance-artefacts (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/assurance-artefacts",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: AssuranceArtefactCreateRequest }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAssuranceArtefactsDependenciesForRequest();
        await createAssuranceArtefact(request, reply, deps);
      });
    }
  );


  // GET /v1/assurance-artefacts (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/assurance-artefacts",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAssuranceArtefactsDependenciesForRequest();
        await listAssuranceArtefacts(request, reply, deps);
      });
    }
  );


  // GET /v1/assurance-artefacts/{artefactId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/assurance-artefacts/:artefactId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { artefactId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getAssuranceArtefactsDependenciesForRequest();
        await getAssuranceArtefact(request, reply, deps);
      });
    }
  );


}
