/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { assuranceArtefactRoutes } from "./assurance-artefact.routes.js";
export { auditorExportRoutes } from "./auditor-export.routes.js";
export { signRoutes } from "./sign.routes.js";
