/**
 * AssuranceArtefact DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AssuranceArtefact DTOs
 *
 * DDD: Application DTOs for AssuranceArtefact use cases.
 */

import type { AssuranceArtefactCreateRequest, GetAssuranceArtefactParams, ListAssuranceArtefactsParams } from "@vericlause/core/assurance-artefacts/types";

export type ListAssuranceArtefactsInput = ListAssuranceArtefactsParams;

export type CreateAssuranceArtefactInput = AssuranceArtefactCreateRequest;

export type GetAssuranceArtefactInput = GetAssuranceArtefactParams;

export type ListAssuranceArtefactsOutput = {};

export type CreateAssuranceArtefactOutput = {};

export type GetAssuranceArtefactOutput = {};
