/**
 * AuditorExport DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AuditorExport DTOs
 *
 * DDD: Application DTOs for AuditorExport use cases.
 */

import type { CreateAuditorExportPackParams } from "@vericlause/core/assurance-artefacts/types";

export type CreateAuditorExportPackInput = CreateAuditorExportPackParams;

export type CreateAuditorExportPackOutput = {};
