/**
 * ApproveRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: waivers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ApproveRepository Port
 *
 * DDD: Application port for approverepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ApproveWaiverInput, ApproveWaiverOutput } from "../dto/approve.dto";
export interface ApproveRepository {
  approveWaiver(input: ApproveWaiverInput): Promise<ApproveWaiverOutput>;
}

export type { ApproveWaiverInput, ApproveWaiverOutput } from "../dto/approve.dto";
