/**
 * WaiverRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: waivers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * WaiverRepository Port
 *
 * DDD: Application port for waiverrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetWaiverInput, GetWaiverOutput, ListWaiversInput, ListWaiversOutput, ProposeWaiverInput, ProposeWaiverOutput } from "../dto/waiver.dto";
export interface WaiverRepository {
  listWaivers(input: ListWaiversInput): Promise<ListWaiversOutput>;
  proposeWaiver(input: ProposeWaiverInput): Promise<ProposeWaiverOutput>;
  getWaiver(input: GetWaiverInput): Promise<GetWaiverOutput>;
}

export type { GetWaiverInput, GetWaiverOutput, ListWaiversInput, ListWaiversOutput, ProposeWaiverInput, ProposeWaiverOutput } from "../dto/waiver.dto";
