/**
 * ExecuteListReleaseGates - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: release-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListReleaseGates Use Case
 *
 * DDD: Application use case for list ReleaseGate.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListReleaseGatesInput, ListReleaseGatesOutput } from "../dto/release-gate.dto";
import type { ExecutionContextService, IdGeneratorService } from "@vericlause/services/_shared/index.js";
import type { ReleaseGateRepository } from "../ports";

export class ExecuteListReleaseGates {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly releaseGate: ReleaseGateRepository
  ) {}

  async execute(input: ListReleaseGatesInput): Promise<ListReleaseGatesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.gatId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.releaseGate.listReleaseGates({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListReleaseGatesOutput;
  }
}
