/**
 * Handlers for Specification
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: specifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { SpecificationsDomainModule } from "../dependencies/specifications-ddd.dependencies.js";
import type { SpecificationCreateRequest, SpecificationUpdateRequest } from "@vericlause/core/specifications/types";
import type { CreateSpecificationInput, GetSpecificationInput, ListSpecificationsInput, UpdateSpecificationInput } from "@vericlause/services/specifications";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/specifications
 * Operation: listSpecifications
 */
export async function listSpecifications(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], projectId?: string | string[], versionRef?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: SpecificationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListSpecificationsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.specifications.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/specifications
 * Operation: createSpecification
 */
export async function createSpecification(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: SpecificationCreateRequest }>,
  reply: FastifyReply,
  deps: SpecificationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateSpecificationInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.specifications.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/specifications/{specId}
 * Operation: getSpecification
 */
export async function getSpecification(
  request: FastifyRequest<{ Params: { specId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: SpecificationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetSpecificationInput = {
    specId: request.params.specId,
  };
  const result = await deps.useCases.specifications.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PATCH /v1/specifications/{specId}
 * Operation: updateSpecification
 */
export async function updateSpecification(
  request: FastifyRequest<{ Params: { specId: string }; Querystring: Record<string, string | string[] | undefined>; Body: SpecificationUpdateRequest }>,
  reply: FastifyReply,
  deps: SpecificationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpdateSpecificationInput = {
    specId: request.params.specId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.specifications.update.execute(input);
  return reply.code(200).send(result);
}


