/**
 * AnalysisJobs DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: analysis-jobs
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AnalysisJobs Domain Module - Composition root
 *
 * DDD: Composition root for analysis-jobs domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AnalysisJobRepositoryAdapter,
} from "@vericlause/adapters/analysis-jobs";
import { getIdGeneratorService } from "@vericlause/adapters";
import type { AdapterDynamoDBClient } from "@vericlause/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateAnalysisJob,
  ExecuteGetAnalysisJob,
  ExecuteListAnalysisJobs,
} from "@vericlause/services/analysis-jobs/usecases";
// Ports (interfaces)
import type {
  AnalysisJobRepository,
} from "@vericlause/services/analysis-jobs/ports";

export interface AnalysisJobsDomainModule {
  repos: {
    analysisJobs: AnalysisJobRepository;
  };
  useCases: {
    analysisJobs: {
      create: ExecuteCreateAnalysisJob;
      get: ExecuteGetAnalysisJob;
      list: ExecuteListAnalysisJobs;
    };
  };
}

export function buildAnalysisJobsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): AnalysisJobsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      analysisJobs?: AnalysisJobRepository;
    } = {};

    obj.analysisJobs = new AnalysisJobRepositoryAdapter(dynamoClient);
    return {
      analysisJobs: obj.analysisJobs!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    analysisJobs: {
      create: new ExecuteCreateAnalysisJob(executionContext, idGenerator, repos.analysisJobs),
      get: new ExecuteGetAnalysisJob(executionContext, idGenerator, repos.analysisJobs),
      list: new ExecuteListAnalysisJobs(executionContext, idGenerator, repos.analysisJobs),
    },
  };
  return { repos, useCases: useCases as AnalysisJobsDomainModule["useCases"] };
}
