/**
 * AssuranceArtefacts DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: assurance-artefacts
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AssuranceArtefacts Domain Module - Composition root
 *
 * DDD: Composition root for assurance-artefacts domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AssuranceArtefactRepositoryAdapter,
  AuditorExportRepositoryAdapter,
  SignRepositoryAdapter,
} from "@vericlause/adapters/assurance-artefacts";
import { getIdGeneratorService } from "@vericlause/adapters";
import type { AdapterDynamoDBClient } from "@vericlause/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateAssuranceArtefact,
  ExecuteCreateAuditorExportPack,
  ExecuteGetAssuranceArtefact,
  ExecuteListAssuranceArtefacts,
  ExecuteSignAssuranceArtefact,
} from "@vericlause/services/assurance-artefacts/usecases";
// Ports (interfaces)
import type {
  AssuranceArtefactRepository,
  AuditorExportRepository,
  SignRepository,
} from "@vericlause/services/assurance-artefacts/ports";

export interface AssuranceArtefactsDomainModule {
  repos: {
    assuranceArtefacts: AssuranceArtefactRepository;
    auditorExports: AuditorExportRepository;
    signs: SignRepository;
  };
  useCases: {
    assuranceArtefacts: {
      create: ExecuteCreateAssuranceArtefact;
      get: ExecuteGetAssuranceArtefact;
      list: ExecuteListAssuranceArtefacts;
    };
    auditorExports: {
      create: ExecuteCreateAuditorExportPack;
    };
    signs: {
      get: ExecuteSignAssuranceArtefact;
    };
  };
}

export function buildAssuranceArtefactsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): AssuranceArtefactsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      assuranceArtefacts?: AssuranceArtefactRepository;
      auditorExports?: AuditorExportRepository;
      signs?: SignRepository;
    } = {};

    obj.assuranceArtefacts = new AssuranceArtefactRepositoryAdapter(dynamoClient);
    obj.auditorExports = new AuditorExportRepositoryAdapter(dynamoClient);
    obj.signs = new SignRepositoryAdapter(dynamoClient);
    return {
      assuranceArtefacts: obj.assuranceArtefacts!,
      auditorExports: obj.auditorExports!,
      signs: obj.signs!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    assuranceArtefacts: {
      create: new ExecuteCreateAssuranceArtefact(executionContext, idGenerator, repos.assuranceArtefacts),
      get: new ExecuteGetAssuranceArtefact(executionContext, idGenerator, repos.assuranceArtefacts),
      list: new ExecuteListAssuranceArtefacts(executionContext, idGenerator, repos.assuranceArtefacts),
    },
    auditorExports: {
      create: new ExecuteCreateAuditorExportPack(executionContext, idGenerator, repos.auditorExports),
    },
    signs: {
      get: new ExecuteSignAssuranceArtefact(executionContext, idGenerator, repos.signs),
    },
  };
  return { repos, useCases: useCases as AssuranceArtefactsDomainModule["useCases"] };
}
