/**
 * ContractProjectRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contract-projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ContractProjectRepository Port
 *
 * DDD: Application port for contractprojectrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateContractProjectInput, CreateContractProjectOutput, GetContractProjectInput, GetContractProjectOutput, ListContractProjectsInput, ListContractProjectsOutput, UpdateContractProjectInput, UpdateContractProjectOutput } from "../dto/contract-project.dto";
export interface ContractProjectRepository {
  listContractProjects(input: ListContractProjectsInput): Promise<ListContractProjectsOutput>;
  createContractProject(input: CreateContractProjectInput): Promise<CreateContractProjectOutput>;
  getContractProject(input: GetContractProjectInput): Promise<GetContractProjectOutput>;
  updateContractProject(input: UpdateContractProjectInput): Promise<UpdateContractProjectOutput>;
}

export type { CreateContractProjectInput, CreateContractProjectOutput, GetContractProjectInput, GetContractProjectOutput, ListContractProjectsInput, ListContractProjectsOutput, UpdateContractProjectInput, UpdateContractProjectOutput } from "../dto/contract-project.dto";
