/**
 * VersionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: contract-projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VersionRepository Port
 *
 * DDD: Application port for versionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateContractVersionInput, CreateContractVersionOutput, GetContractVersionInput, GetContractVersionOutput, ListContractVersionsInput, ListContractVersionsOutput } from "../dto/version.dto";
export interface VersionRepository {
  listContractVersions(input: ListContractVersionsInput): Promise<ListContractVersionsOutput>;
  createContractVersion(input: CreateContractVersionInput): Promise<CreateContractVersionOutput>;
  getContractVersion(input: GetContractVersionInput): Promise<GetContractVersionOutput>;
}

export type { CreateContractVersionInput, CreateContractVersionOutput, GetContractVersionInput, GetContractVersionOutput, ListContractVersionsInput, ListContractVersionsOutput } from "../dto/version.dto";
