/**
 * Repository interface for ContractProject
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: contract-projects
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateUpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ContractProjectEntity
} from "../models/contract-project.entity.js";
import type {
  ListContractProjectsParams,
  ContractProjectCreateRequest,
  UpdateContractProjectRequestInput
} from "../types/index.js";
/**
 * ContractProjectRepository Interface
 */
export interface ContractProjectRepository extends CreateUpdateReadRepository<ContractProjectEntity, ContractProjectCreateRequest, UpdateContractProjectRequestInput, string, ListContractProjectsParams> {

}
