/**
 * Repository interface for ReleaseGate
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: release-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ReleaseGateEntity
} from "../models/release-gate.entity.js";
import type {
  ListReleaseGatesParams,
  ReleaseGateCreateRequest
} from "../types/index.js";
/**
 * ReleaseGateRepository Interface
 */
export interface ReleaseGateRepository extends CreateReadRepository<ReleaseGateEntity, ReleaseGateCreateRequest, string, ListReleaseGatesParams> {

}
