/**
 * FindingRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: findings
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FindingRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements FindingRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  FindingRepository,
} from "@vericlause/services/findings";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { FindingRepositoryDdb } from "./finding-repository.ddb.js";

/**
 * FindingRepositoryAdapter
 *
 * Implements FindingRepository port for infrastructure layer.
 */
export class FindingRepositoryAdapter implements FindingRepository {
  private readonly ddb: FindingRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new FindingRepositoryDdb(this.dynamoClient);
  }

  async listFindings(input: Parameters<FindingRepository['listFindings']>[0]): Promise<Awaited<ReturnType<FindingRepository['listFindings']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listFindings(input);
  }

  async createFinding(input: Parameters<FindingRepository['createFinding']>[0]): Promise<Awaited<ReturnType<FindingRepository['createFinding']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createFinding(input);
  }

  async getFinding(input: Parameters<FindingRepository['getFinding']>[0]): Promise<Awaited<ReturnType<FindingRepository['getFinding']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getFinding(input);
  }
}
